### ISSUE TITLE
Paper inquiry | Exact match accuracy with or without values?

### ISSUE THREAD

**Issue by klima7** [ai-spiderweb/pauq#1]
My question is about Your article. I would like to know whether You have used exact match accuracy with or without values in Your results. 
It is not said directly and I'm confused because, on the one hand, You have paid very close attention to translating values and adding them to the database, and on the other hand, RAT-SQL is a model that generally does not predict values.

I would be very gratefull for clarification.

**Comment by runnerup96** [comment]
Hello!
We have used exact match with values.

We used this implementation - https://github.com/berlino/tensor2struct-public/tree/main
